#line 2 "token.c"

#line 4 "token.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer liberty_parser2__create_buffer
#define yy_delete_buffer liberty_parser2__delete_buffer
#define yy_scan_buffer liberty_parser2__scan_buffer
#define yy_scan_string liberty_parser2__scan_string
#define yy_scan_bytes liberty_parser2__scan_bytes
#define yy_init_buffer liberty_parser2__init_buffer
#define yy_flush_buffer liberty_parser2__flush_buffer
#define yy_load_buffer_state liberty_parser2__load_buffer_state
#define yy_switch_to_buffer liberty_parser2__switch_to_buffer
#define yypush_buffer_state liberty_parser2_push_buffer_state
#define yypop_buffer_state liberty_parser2_pop_buffer_state
#define yyensure_buffer_stack liberty_parser2_ensure_buffer_stack
#define yy_flex_debug liberty_parser2__flex_debug
#define yyin liberty_parser2_in
#define yyleng liberty_parser2_leng
#define yylex liberty_parser2_lex
#define yylineno liberty_parser2_lineno
#define yyout liberty_parser2_out
#define yyrestart liberty_parser2_restart
#define yytext liberty_parser2_text
#define yywrap liberty_parser2_wrap
#define yyalloc liberty_parser2_alloc
#define yyrealloc liberty_parser2_realloc
#define yyfree liberty_parser2_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define liberty_parser2__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer liberty_parser2__create_buffer
#endif

#ifdef yy_delete_buffer
#define liberty_parser2__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer liberty_parser2__delete_buffer
#endif

#ifdef yy_scan_buffer
#define liberty_parser2__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer liberty_parser2__scan_buffer
#endif

#ifdef yy_scan_string
#define liberty_parser2__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string liberty_parser2__scan_string
#endif

#ifdef yy_scan_bytes
#define liberty_parser2__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes liberty_parser2__scan_bytes
#endif

#ifdef yy_init_buffer
#define liberty_parser2__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer liberty_parser2__init_buffer
#endif

#ifdef yy_flush_buffer
#define liberty_parser2__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer liberty_parser2__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define liberty_parser2__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state liberty_parser2__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define liberty_parser2__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer liberty_parser2__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define liberty_parser2_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state liberty_parser2_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define liberty_parser2_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state liberty_parser2_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define liberty_parser2_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack liberty_parser2_ensure_buffer_stack
#endif

#ifdef yylex
#define liberty_parser2_lex_ALREADY_DEFINED
#else
#define yylex liberty_parser2_lex
#endif

#ifdef yyrestart
#define liberty_parser2_restart_ALREADY_DEFINED
#else
#define yyrestart liberty_parser2_restart
#endif

#ifdef yylex_init
#define liberty_parser2_lex_init_ALREADY_DEFINED
#else
#define yylex_init liberty_parser2_lex_init
#endif

#ifdef yylex_init_extra
#define liberty_parser2_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra liberty_parser2_lex_init_extra
#endif

#ifdef yylex_destroy
#define liberty_parser2_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy liberty_parser2_lex_destroy
#endif

#ifdef yyget_debug
#define liberty_parser2_get_debug_ALREADY_DEFINED
#else
#define yyget_debug liberty_parser2_get_debug
#endif

#ifdef yyset_debug
#define liberty_parser2_set_debug_ALREADY_DEFINED
#else
#define yyset_debug liberty_parser2_set_debug
#endif

#ifdef yyget_extra
#define liberty_parser2_get_extra_ALREADY_DEFINED
#else
#define yyget_extra liberty_parser2_get_extra
#endif

#ifdef yyset_extra
#define liberty_parser2_set_extra_ALREADY_DEFINED
#else
#define yyset_extra liberty_parser2_set_extra
#endif

#ifdef yyget_in
#define liberty_parser2_get_in_ALREADY_DEFINED
#else
#define yyget_in liberty_parser2_get_in
#endif

#ifdef yyset_in
#define liberty_parser2_set_in_ALREADY_DEFINED
#else
#define yyset_in liberty_parser2_set_in
#endif

#ifdef yyget_out
#define liberty_parser2_get_out_ALREADY_DEFINED
#else
#define yyget_out liberty_parser2_get_out
#endif

#ifdef yyset_out
#define liberty_parser2_set_out_ALREADY_DEFINED
#else
#define yyset_out liberty_parser2_set_out
#endif

#ifdef yyget_leng
#define liberty_parser2_get_leng_ALREADY_DEFINED
#else
#define yyget_leng liberty_parser2_get_leng
#endif

#ifdef yyget_text
#define liberty_parser2_get_text_ALREADY_DEFINED
#else
#define yyget_text liberty_parser2_get_text
#endif

#ifdef yyget_lineno
#define liberty_parser2_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno liberty_parser2_get_lineno
#endif

#ifdef yyset_lineno
#define liberty_parser2_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno liberty_parser2_set_lineno
#endif

#ifdef yywrap
#define liberty_parser2_wrap_ALREADY_DEFINED
#else
#define yywrap liberty_parser2_wrap
#endif

#ifdef yyalloc
#define liberty_parser2_alloc_ALREADY_DEFINED
#else
#define yyalloc liberty_parser2_alloc
#endif

#ifdef yyrealloc
#define liberty_parser2_realloc_ALREADY_DEFINED
#else
#define yyrealloc liberty_parser2_realloc
#endif

#ifdef yyfree
#define liberty_parser2_free_ALREADY_DEFINED
#else
#define yyfree liberty_parser2_free
#endif

#ifdef yytext
#define liberty_parser2_text_ALREADY_DEFINED
#else
#define yytext liberty_parser2_text
#endif

#ifdef yyleng
#define liberty_parser2_leng_ALREADY_DEFINED
#else
#define yyleng liberty_parser2_leng
#endif

#ifdef yyin
#define liberty_parser2_in_ALREADY_DEFINED
#else
#define yyin liberty_parser2_in
#endif

#ifdef yyout
#define liberty_parser2_out_ALREADY_DEFINED
#else
#define yyout liberty_parser2_out
#endif

#ifdef yy_flex_debug
#define liberty_parser2__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug liberty_parser2__flex_debug
#endif

#ifdef yylineno
#define liberty_parser2_lineno_ALREADY_DEFINED
#else
#define yylineno liberty_parser2_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define liberty_parser2_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[127] =
    {   0,
        0,    0,   28,   28,    0,    0,   37,   37,   42,   41,
       23,   20,   22,   24,   25,   27,    7,    8,    3,    1,
        5,    2,   14,    4,   14,   12,    6,   25,    9,   25,
       25,   41,   25,   25,   10,   11,   28,   30,   29,   36,
       33,   32,   41,   38,   37,   39,   40,   12,   25,    0,
       25,    0,   25,   14,   14,   14,   14,   25,   26,   14,
       14,   25,    6,   25,   25,    0,   20,   25,   25,   11,
       11,   28,   29,   29,   31,   36,   35,   34,   38,   37,
        0,   25,   14,   25,   25,   14,   14,   25,   25,   14,
       25,   25,   21,   25,   25,   15,   15,   25,   14,   25,

       14,   25,   18,   25,   25,   19,   25,   25,   16,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       17,   25,    0,   13,   13,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    6,    6,   22,    6,    6,    6,   23,   24,
        6,    6,    6,    6,    6,   25,    6,    6,    6,    6,
        6,   26,   27,   28,   29,    6,    6,    6,    6,    6,
       30,   31,   32,    6,   33,    1,   22,    6,   34,   35,

       36,   37,   38,    6,   39,    6,    6,   40,    6,   41,
       42,   43,    6,   44,   27,   28,   45,    6,    6,    6,
        6,    6,   46,    6,   47,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    2,    3,    1,    2,    4,    5,    6,    2,    7,
        4,    1,    8,    8,    1,    4,    6,    2,    4,    1,
        8,    4,    4,    4,    4,    4,    4,    4,    4,    6,
        5,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    6,    1
    } ;

static const flex_int16_t yy_base[138] =
    {   0,
        0,    0,   45,   46,   47,   50,   56,   61,  172,  413,
      146,  413,  413,  120,   74,  413,  413,  413,  413,  113,
      413,   46,   53,  113,   61,   64,   94,    0,  413,   76,
       87,  103,   86,   95,  413,  123,    0,  413,   58,    0,
      413,  413,  112,    0,  112,  413,  413,  413,  102,  122,
        0,  125,  129,  124,  134,  138,  133,  151,  413,  142,
      152,  166,  171,  167,  170,  188,  413,  171,  180,  193,
      413,    0,   70,  109,  413,    0,  413,  413,    0,  195,
      196,  209,  187,  218,   91,   70,  204,  208,   55,   51,
      219,  222,  413,  223,  228,  413,    0,  137,  188,   36,

       35,  234,  233,  237,  238,  245,  249,  253,  257,  250,
      258,  261,  265,  266,  273,  277,  281,  284,  285,  291,
      288,  306,  327,  317,  413,  413,  335,  343,  351,  356,
      361,  366,  372,  380,  388,  396,  404
    } ;

static const flex_int16_t yy_def[138] =
    {   0,
      126,    1,  127,  127,  128,  128,  129,  129,  126,  126,
      126,  126,  126,  126,  130,  126,  126,  126,  126,  130,
      126,  131,  131,  126,  131,  132,  126,  131,  126,   20,
       20,  126,   20,   20,  126,  126,  133,  126,  134,  135,
      126,  126,  136,  137,  126,  126,  126,  126,   20,  126,
      131,  132,  131,  131,   20,  131,  131,  131,  126,  131,
      131,  131,  126,   20,   20,  126,  126,   20,   20,  126,
      126,  133,  134,  134,  126,  135,  126,  126,  137,  126,
      126,  131,   20,   20,  131,  131,  131,  131,  131,  131,
       20,   20,  126,   20,   20,  126,  131,   20,   20,  131,

      131,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  126,  126,  126,    0,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126
    } ;

static const flex_int16_t yy_nxt[461] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       28,   15,   15,   30,   15,   15,   15,   31,   15,   10,
       32,   10,   15,   15,   33,   15,   30,   15,   34,   15,
       15,   15,   15,   15,   15,   35,   36,   38,   38,   41,
      101,  101,   41,   42,   39,   39,   42,   45,   10,   54,
       45,   56,   45,   10,   46,   45,   90,   74,   57,   46,
       90,   50,   75,   47,   60,   58,   61,   43,   47,  126,
       43,   50,   50,   62,  126,   86,   51,   51,   58,   51,
       52,   49,   53,   50,   51,   63,   62,   64,   63,   51,

       51,   49,   49,   50,   66,   67,   86,   66,   51,   50,
       49,   63,   65,   80,   78,   51,   80,   49,   74,   50,
       50,   68,   59,   75,   70,   51,   54,   70,   55,   52,
       65,   53,   50,   51,   81,   69,   48,   81,   81,   57,
       71,   82,   50,   50,   82,   81,   58,   60,   57,   83,
       51,   60,   99,   61,   50,   58,   84,   87,   50,   58,
       62,   85,   48,   85,   88,   60,   86,   61,   58,   84,
       50,  126,   63,   62,   62,   63,   89,   88,   89,  126,
       51,   90,   49,   51,   51,   49,   49,   62,   63,   66,
       93,   91,   66,   51,   70,   49,   80,   70,   92,   80,

       60,   51,   83,   99,   96,  126,   91,   94,   81,   84,
       71,   81,   81,   95,   92,  126,   96,   96,  100,   87,
      100,   82,   84,  101,   82,   81,   88,   96,   98,   97,
       89,   51,   51,   99,   49,   51,   51,   49,   49,   88,
       96,   51,   96,   49,  103,  102,   51,   51,   49,   49,
       51,   51,   49,   49,  126,   96,  106,  103,   51,  126,
       49,  104,   51,   51,   49,   49,   51,  105,   49,  106,
       51,   51,   49,   49,   51,  126,   49,  107,   51,   51,
       49,   49,  108,  126,  109,  112,   51,  110,   49,  111,
       51,  126,   49,  114,   51,  113,   49,   51,   51,   49,

       49,   51,  116,   49,   51,  126,   49,  123,  115,  126,
      123,  126,  126,  124,  117,  118,  126,  126,  126,   51,
      126,   49,  126,  120,  126,  119,  122,  121,  123,   81,
      126,  123,   81,   81,  125,   37,   37,   37,   37,   37,
       37,   37,   37,   40,   40,   40,   40,   40,   40,   40,
       40,   44,   44,   44,   44,   44,   44,   44,   44,   49,
      126,   49,  126,   49,   51,  126,  126,  126,   51,   52,
      126,   52,   72,   72,  126,   72,   72,   72,  126,   72,
       73,   73,  126,   73,   73,   73,   73,   73,   76,   76,
      126,   76,  126,   76,   76,   76,   77,   77,   77,   77,

       77,   77,   77,   77,   79,  126,  126,   79,   79,   79,
       79,   79,    9,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126
    } ;

static const flex_int16_t yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
      101,  100,    6,    5,    3,    4,    6,    7,    7,   22,
        7,   22,    8,    8,    7,    8,   90,   39,   23,    8,
       89,   26,   39,    7,   25,   23,   25,    5,    8,   73,
        6,   15,   26,   25,   73,   86,   15,   15,   23,   30,
       15,   30,   15,   26,   15,   27,   25,   30,   27,   33,

       31,   33,   31,   15,   32,   32,   85,   32,   34,   26,
       34,   27,   31,   45,   43,   49,   45,   49,   74,   15,
       20,   33,   24,   74,   36,   20,   20,   36,   20,   20,
       31,   20,   52,   20,   50,   34,   14,   50,   50,   54,
       36,   53,   20,   52,   53,   53,   54,   55,   57,   55,
       98,   56,   98,   56,   52,   57,   55,   60,   20,   54,
       56,   58,   11,   58,   60,   61,   58,   61,   57,   55,
       52,    9,   63,   56,   61,   63,   62,   60,   62,    0,
       64,   62,   64,   65,   68,   65,   68,   61,   63,   66,
       66,   64,   66,   69,   70,   69,   80,   70,   65,   80,

       83,   99,   83,   99,   81,    0,   64,   68,   81,   83,
       70,   81,   81,   69,   65,    0,   81,   82,   88,   87,
       88,   82,   83,   88,   82,   82,   87,   81,   84,   82,
       84,   84,   91,   84,   91,   92,   94,   92,   94,   87,
       82,   95,   81,   95,   92,   91,  103,  102,  103,  102,
      104,  105,  104,  105,    0,   82,  102,   92,  106,    0,
      106,   94,  107,  110,  107,  110,  108,   95,  108,  102,
      109,  111,  109,  111,  112,    0,  112,  104,  113,  114,
      113,  114,  105,    0,  107,  110,  115,  108,  115,  109,
      116,    0,  116,  112,  117,  111,  117,  118,  119,  118,

      119,  121,  114,  121,  120,    0,  120,  122,  113,    0,
      122,    0,    0,  122,  115,  116,    0,    0,    0,  122,
        0,  122,    0,  118,    0,  117,  120,  119,  123,  124,
        0,  123,  124,  124,  123,  127,  127,  127,  127,  127,
      127,  127,  127,  128,  128,  128,  128,  128,  128,  128,
      128,  129,  129,  129,  129,  129,  129,  129,  129,  130,
        0,  130,    0,  130,  131,    0,    0,    0,  131,  132,
        0,  132,  133,  133,    0,  133,  133,  133,    0,  133,
      134,  134,    0,  134,  134,  134,  134,  134,  135,  135,
        0,  135,    0,  135,  135,  135,  136,  136,  136,  136,

      136,  136,  136,  136,  137,    0,    0,  137,  137,  137,
      137,  137,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "token.l"
#line 3 "token.l"
/******************************************************************************
    Copyright (c) 1996-2005 Synopsys, Inc.    ALL RIGHTS RESERVED

  The contents of this file are subject to the restrictions and limitations
  set forth in the SYNOPSYS Open Source License Version 1.0  (the "License"); 
  you may not use this file except in compliance with such restrictions 
  and limitations. You may obtain instructions on how to receive a copy of 
  the License at

  http://www.synopsys.com/partners/tapin/tapinprogram.html. 

  Software distributed by Original Contributor under the License is 
  distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
  expressed or implied. See the License for the specific language governing 
  rights and limitations under the License.

******************************************************************************/
struct xnumber
{
	int type; /* 0=int, 1=float */
	int intnum;
	double floatnum;
};
typedef struct xnumber xnumber;

#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <string.h>
#include "liberty_structs.h"
#include "si2dr_liberty.h"
#include "liberty_parser.h"
#include "libhash.h"
#include "libstrtab.h"
#ifdef DMALLOC
#include <dmalloc.h>
#define my_strdup(ptr) dmalloc_strdup(__FILE__, __LINE__, (ptr), 0)

#else
#include "mymalloc.h"
char *my_strdup(char *str);

char *my_strdup(char *str){ char *x = my_malloc(strlen(str)+3 /* just in case of insertions */); strcpy(x,str); return x;}

#endif

int liberty_parser2_lex(void);


extern liberty_strtable *master_string_table;

/* I added this code to avoid a confusion between bus notation and a complex attr with a single integer value. */

typedef struct token_q
{
  int retval;  /* the token value to return */
  int set_num; /* set the yylval to contain the num; -1 is an int; +1 is a float */
  double floatnum;  /* number to put to yylval */
  int intnum;  /* number to put to yylval */
  char *str;   /* if non-zero, put to yylval */
} token_q;

int token_q_front = 9;
int token_q_rear = 9;

token_q token_q_buf[10];

int token_q_empty(void);

int token_q_empty(void)
{
	if (token_q_front == token_q_rear)
		return 1;
	else
		return 0;
}

static void remove_token(int *retval, int *set_num, int *intnum, double *floatnum, char **str)
{
	if( token_q_empty() )
		return;
		
	if( token_q_front == 9 )
		token_q_front = 0;
	else
		token_q_front++;
	*retval = token_q_buf[token_q_front].retval;
	*set_num = token_q_buf[token_q_front].set_num;
	*floatnum = token_q_buf[token_q_front].floatnum;
	*intnum = token_q_buf[token_q_front].floatnum;
	if( token_q_buf[token_q_front].str )
	{
		*str = token_q_buf[token_q_front].str;
	}
}

static void add_token(int retval, int set_num, int intnum, double floatnum, char *str)
{
	if( token_q_rear == 9 )
		token_q_rear = 0;
	else
		token_q_rear++;

	if( token_q_rear == token_q_front )
	{
		printf("Token Queue Stack Overflow-- notify program maintainers!\n");
		return;
	}
	token_q_buf[token_q_rear].str = str;
	token_q_buf[token_q_rear].retval = retval;
	token_q_buf[token_q_rear].floatnum = floatnum;
	token_q_buf[token_q_rear].intnum = intnum;
	token_q_buf[token_q_rear].set_num = set_num;
}

/* this routine is called from liberty_front_lex.c; which is acting
    as a front end to this lexer */

int injected_token(void);

int injected_token(void)
{
	char *str; 
	double num; 
	int  intnum; 
	int retval; 
	int set_num;

	remove_token(&retval,&set_num,&intnum,&num,&str);

	if( set_num == -1)
    { 
		liberty_parser_lval.num.type = 0;
		liberty_parser_lval.num.intnum = intnum;
	}
	else if(set_num == 1)
	{
		liberty_parser_lval.num.type = 1;
		liberty_parser_lval.num.floatnum = num;
	}
	else if(str)
	{
		liberty_parser_lval.str = str;
	}
	return retval;
}

int tok_encountered = 0;

static int lline;
extern int lineno;
int save_lineno, save_lline;
int tight_colon_ok = 0;
static char filenamebuf[1024];
static char string_buf[80960];
char token_comment_buf[SI2DR_MAX_STRING_LEN]; /* the buffer to hold comments in */
char token_comment_buf2[SI2DR_MAX_STRING_LEN]; /* the spare buffer to hold more comments in */
int comment_overflow=0;
static char *string_buf_ptr;
struct nl
{
	char *fname;
	struct nl *next;
};
struct nl  *file_name_list;

void set_tok(void);

void set_tok(void)
{
	if( token_comment_buf[0] )
		tok_encountered++;
}

char *curr_file, *curr_file_save; 
#define MAX_INCLUDE_DEPTH 1
void clean_file_name(char *,char *);
int include_stack_index = 0;
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];

char *search_string_for_linefeeds(char *str);
#line 1029 "token.c"

#line 1031 "token.c"

#define INITIAL 0
#define comment 1
#define stringx 2
#define include 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 192 "token.l"

#line 1253 "token.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 127 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 413 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 193 "token.l"
{lline = lineno;set_tok(); return PLUS;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 194 "token.l"
{lline = lineno;set_tok(); return MINUS;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 195 "token.l"
{lline = lineno;set_tok(); return MULT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 196 "token.l"
{lline = lineno;set_tok(); return DIV;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 197 "token.l"
{lline = lineno;set_tok(); return COMMA;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 198 "token.l"
{lline = lineno;set_tok(); return SEMI;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 199 "token.l"
{lline = lineno;set_tok(); return LPAR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 200 "token.l"
{lline = lineno;set_tok(); return RPAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 201 "token.l"
{lline = lineno;set_tok(); return EQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 202 "token.l"
{if(lline != lineno) {printf("Warning: line %d: Opening Curly must be on same line as group declaration!\n", lineno);} set_tok(); return LCURLY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 203 "token.l"
{lline = lineno;set_tok(); return RCURLY;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 204 "token.l"
{lline = lineno;if( yyleng == 1 && !tight_colon_ok )printf("Error: space must precede Colon (:) at line %d\n", lineno); set_tok(); return COLON;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 205 "token.l"
BEGIN(include);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 208 "token.l"
{lline = lineno; if(strchr(yytext,'.') || strchr(yytext,'E') || strchr(yytext,'e')) 
																							{liberty_parser_lval.num.type=1;liberty_parser_lval.num.floatnum = strtod(yytext,(char**)NULL); } 
																							else 
																							{liberty_parser_lval.num.type=0;liberty_parser_lval.num.intnum = strtol(yytext,(char**)NULL,10); } 
																			set_tok(); return NUM;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 215 "token.l"
{
 lline = lineno;
 if( !strncmp(yytext,"values(",7) )
 {
   /* ugh -- a values() with a single unquoted number in it! let's translate it into a values with a single quoted value instead! */
   char *ident = liberty_strtable_enter_string(master_string_table, "values"); /* OLD WAY: (char*)malloc(7); */
   char *str /* OLD WAY: = (char*)malloc(strlen(yytext)-4) */;
   /* strcpy(ident,"values");  OLD allocation method */
   liberty_parser_lval.str = ident;
   str = liberty_strtable_enter_string(master_string_table, yytext+7);
   /* OLD WAY: strcpy(str,yytext+7); 
	           str[strlen(str)-1] = 0; */
   add_token(LPAR, 0, 0, 0.0, 0);
   add_token(STRING, 0, 0, 0.0, str);
   add_token(RPAR, 0, 0, 0.0, 0);
   set_tok(); return IDENT;
 }
 else
 {
   /* OLD:  char *str = (char*)malloc(strlen(yytext)+1);
            strcpy(str,yytext)*/ ;  
	liberty_parser_lval.str = /* OLD: str  NEW: */ liberty_strtable_enter_string(master_string_table, yytext);
  set_tok(); return STRING;
 }
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 241 "token.l"
{lline = lineno;set_tok(); return KW_DEFINE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 242 "token.l"
{lline = lineno;set_tok(); return KW_DEFINE_GROUP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 243 "token.l"
{lline = lineno;set_tok(); return KW_TRUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 244 "token.l"
{lline = lineno;set_tok(); return KW_FALSE;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 245 "token.l"
{lineno++;}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 246 "token.l"
{printf("ERROR-- %s:%d -- Continuation char followed by spaces or tabs!\n\n", curr_file, lineno); lineno++; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 247 "token.l"
{}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 248 "token.l"
{}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 249 "token.l"
{}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 251 "token.l"
{lline = lineno;liberty_parser_lval.str = /* OLD: my_strdup(yytext) NEW: */ liberty_strtable_enter_string(master_string_table, yytext); set_tok(); return IDENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 254 "token.l"
{ BEGIN(comment); if (comment_overflow == 0) { 
   if( !tok_encountered && token_comment_buf[0] ) {
      if (strlen(token_comment_buf) + 1> SI2DR_MAX_STRING_LEN-1)  
         comment_overflow = 1; 
      else 
         strcat(token_comment_buf,"\n"); 
   } else if( tok_encountered && token_comment_buf2[0] ) {
      if(strlen(token_comment_buf2)+1 > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1; 
      else 
         strcat(token_comment_buf2,"\n"); }}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 265 "token.l"
string_buf_ptr = string_buf; BEGIN(stringx);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 267 "token.l"
/* eat anything that's not a '*' */ {if(comment_overflow == 0) {
   if( tok_encountered ) {
      if (strlen(token_comment_buf2)+ yyleng > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1; 
      else
         strcat(token_comment_buf2,yytext);
   } else {
      if (strlen(token_comment_buf)+ yyleng > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1;
      else 
         strcat(token_comment_buf,yytext);}}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 278 "token.l"
/* eat up '*'s not followed by '/'s */{ if(comment_overflow == 0) {
   if( tok_encountered ) {
      if (strlen(token_comment_buf2)+ yyleng > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1; 
      else strcat(token_comment_buf2,yytext);
   } else {
      if (strlen(token_comment_buf)+ yyleng > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1; 
      else
         strcat(token_comment_buf,yytext);}}}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 289 "token.l"
{++lineno;if(comment_overflow == 0) {
   if( tok_encountered )  {
      if (strlen(token_comment_buf2)+ yyleng > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1; 
      else 
         strcat(token_comment_buf2,yytext); 
   } else {
      if (strlen(token_comment_buf) +1 > SI2DR_MAX_STRING_LEN-1) 
         comment_overflow =1;
      else 
         strcat(token_comment_buf,"\n");}}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 300 "token.l"
{if (comment_overflow){
   if( tok_encountered ) 
      token_comment_buf2[0] = 0; 
   else 
      token_comment_buf[0]=0; 
      comment_overflow=0; printf("\nWarning: line %d: Comment exceed max size allowed(1M), it will be discards!\n", lineno++); } BEGIN(INITIAL);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 307 "token.l"
{ char *x; BEGIN(INITIAL); *string_buf_ptr = 0;
			liberty_parser_lval.str = liberty_strtable_enter_string(master_string_table, string_buf);/* OLD: my_strdup(string_buf); */ set_tok(); return STRING; }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 310 "token.l"
{ char *x; printf("Error, line %d: unterminated string constant-- use a back-slash to continue a string to the next line.\n", lineno++); 
			BEGIN(INITIAL); *string_buf_ptr = 0;
			liberty_parser_lval.str = liberty_strtable_enter_string(master_string_table, string_buf);/* OLD: my_strdup(string_buf);*/ set_tok(); return STRING;
		}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 314 "token.l"
{ *string_buf_ptr++ = '\\'; *string_buf_ptr++ = '\n'; lineno++;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 315 "token.l"
{ *string_buf_ptr++ = '\\'; *string_buf_ptr++ = yytext[1];}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 316 "token.l"
{ char *yptr = yytext; while (*yptr) *string_buf_ptr++ = *yptr++; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 318 "token.l"
{}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 319 "token.l"
{  
                 if ( include_stack_index >= MAX_INCLUDE_DEPTH )
                     {
                     fprintf( stderr, "******Error: Includes nested too deeply! An included file cannot include another file!\n\n" );
                     exit( 1 );
                     }
				 clean_file_name(yytext,filenamebuf);
                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 327 "token.l"
{}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 328 "token.l"
{ FILE *yyin_save = yyin; struct nl *nlp;
 
                 include_stack[include_stack_index++] = YY_CURRENT_BUFFER;
					printf("       ... including file %s\n", filenamebuf);
                 yyin = fopen( filenamebuf, "r" );
			
                 if ( ! yyin )
				{
					
					fprintf(stderr,"******Error: Couldn't find the include file: %s; ignoring the Include directive!\n", filenamebuf);
                     include_stack_index--;
					yyin = yyin_save;
					BEGIN(INITIAL);
				}
				else
				{
                 yy_switch_to_buffer(
                     yy_create_buffer( yyin, YY_BUF_SIZE ) );
				 nlp = (struct nl*)calloc(sizeof(struct nl),1);
				 nlp->fname = /*OLD: (char*)malloc(strlen(filenamebuf)+1); NEW:*/ liberty_strtable_enter_string(master_string_table, filenamebuf);
				              /*OLD: strcpy(nlp->fname,filenamebuf); */
				 nlp->next = file_name_list;
				 file_name_list = nlp;
				 curr_file_save = curr_file;
				 curr_file = nlp->fname;
				 save_lineno = lineno;
				 save_lline = lline;
				 lineno = 1;
				 lline = 1;
                 BEGIN(INITIAL);
				}
         }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(stringx):
case YY_STATE_EOF(include):
#line 362 "token.l"
{
                 if ( --include_stack_index < 0 )
                     {
                     yyterminate();
                     }

                 else
                     {
						 yy_delete_buffer( YY_CURRENT_BUFFER );
						 yy_switch_to_buffer(include_stack[include_stack_index] );
						 lineno = save_lineno;
						 lline = save_lline;
						 curr_file = curr_file_save;
                     }
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 378 "token.l"
ECHO;
	YY_BREAK
#line 1655 "token.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 127 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 127 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 126);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 378 "token.l"


void clean_file_name(char *dirty, char *clean)
{
	/* clean (no quotes, no spaces) the name;
       then make sure it exists in the current dir or the path; if 
       it exists in the path, plug in the path component into the name,
       so the later fopen will find it */
	char cleanbuf[4096],*p,anotherbuf[4096];
	p = dirty;
	
    while( *p && (*p == '"' || *p == ' ' || *p == '\t' ) )
	{
		*p++;
	}
	
	strcpy( cleanbuf, p);
	
	p = cleanbuf + strlen(cleanbuf) -1;

	while (*p && p > cleanbuf && (*p == '"' || *p == ' ' || *p == '\t' ) )
		*p-- = 0;
	if( access(cleanbuf, F_OK ) == 0 )
	{
		strcpy(clean, cleanbuf);
		return;
	}
	else
	{
		/* hmmm, not in the current directory? */
		char enbuf[20256];
		
		char *en = getenv("LIBERTY_PARSER_SEARCH_PATH");
		if( !en )
		{
			strcpy(clean, cleanbuf);
			return;
		}
		else
		{
			char *q;
			
			strcpy(enbuf,en);
			strcat(enbuf,":");
			q = enbuf;
			
			while( q && *q && (p = strchr(q,':') ) )
			{
				*p = 0;
				
				if( p>enbuf && (*(p-1) == '/' || *(p-1) == '\\'))
					*(p-1) = 0;
				
				strcpy(anotherbuf,q);
				strcat(anotherbuf,"/");
				strcat(anotherbuf,cleanbuf);
				
				if( access(anotherbuf,F_OK) == 0 )
				{
					strcpy(clean,anotherbuf);
					return;
				}
				
				q = p+1;
			}
		}
	}
}

char *search_string_for_linefeeds(char *str)
{
   char *s;
   s = str;
   while (*s){ if( *s++ == '\n' ) {lineno++; if( *(s-2) != '\\' ){printf("Warning: line %d: String constant spanning input lines does not use continuation character.\n",lineno);} } }
   return str;
}


